version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Iniciando criação da infraestrutura..."
      - terraform init infra/
      - terraform apply -auto-approve infra/
artifacts:
  files:
    - '**/*'
